mockData = [{'visitorId': '1aUserOne', 'pageUrl': 'mock.com/home', 'timestamp': 1},
            {'visitorId': '1aUserOne', 'pageUrl': 'mock.com/home/afterhome', 'timestamp': 10},
            {'visitorId': '1aUserOne', 'pageUrl': 'mock.com/home/afterhome/afterafterhome', 'timestamp': 100},
            {'visitorId': '2bUserTwo', 'pageUrl': 'mock.com/home', 'timestamp': 32},
            {'visitorId': '1aUserOne', 'pageUrl': 'mock.com/home', 'timestamp': 1000},
            {'visitorId': '2bUserTwo', 'pageUrl': 'mock.com/home/afterhome', 'timestamp': 67},
            {'visitorId': '1aUserOne', 'pageUrl': 'mock.com/home/thisshouldbealone', 'timestamp': 10000},
            {'visitorId': '3cUserThree', 'pageUrl': 'mock.com/home/afterhome/afterafterhome', 'timestamp': 8932},
            {'visitorId': '3cUserThree', 'pageUrl': 'mock.com/home', 'timestamp': 23323},
            {'visitorId': '3cUserThree', 'pageUrl': 'mock.com/home/thisshouldbealone', 'timestamp': 324142}]

mockData2 = [{'visitorId': '1aUserOne', 'pageUrl': 'mock.com/home', 'timestamp': 1},
             {'visitorId': '1aUserOne', 'pageUrl': 'mock.com/home/afterhome', 'timestamp': 10},
             {'visitorId': '1aUserOne', 'pageUrl': 'mock.com/home/afterhome/afterafterhome', 'timestamp': 100000},
             {'visitorId': '2bUserTwo', 'pageUrl': 'mock.com/home', 'timestamp': 32},
             {'visitorId': '1aUserOne', 'pageUrl': 'mock.com/home', 'timestamp': 1000},
             {'visitorId': '2bUserTwo', 'pageUrl': 'mock.com/home/afterhome', 'timestamp': 67},
             {'visitorId': '1aUserOne', 'pageUrl': 'mock.com/home/thispageisdifferent', 'timestamp': 10000},
             {'visitorId': '3cUserThree', 'pageUrl': 'mock.com/home/afterhome/afterafterhome', 'timestamp': 8932},
             {'visitorId': '3cUserThree', 'pageUrl': 'mock.com/home', 'timestamp': 23323},
             {'visitorId': '3cUserThree', 'pageUrl': 'mock.com/home/thisshouldbealone', 'timestamp': 324142},
             {'visitorId': '4dUserFour', 'pageUrl': 'mock.com/home', 'timestamp': 34},
             {'visitorId': '5eUserFive', 'pageUrl': 'mock.com/home', 'timestamp': 10001},
             {'visitorId': '4dUserFour', 'pageUrl': 'mock.com/home/afterhome', 'timestamp': 68},
             {'visitorId': '5eUserFive', 'pageUrl': 'mock.com/home/thispageisdifferent', 'timestamp': 100001},
             {'visitorId': '6fUserSix', 'pageUrl': 'mock.com/home/afterhome/afterafterhome', 'timestamp': 89323},
             {'visitorId': '6fUserSix', 'pageUrl': 'mock.com/home', 'timestamp': 233233},
             {'visitorId': '6fUserSix', 'pageUrl': 'mock.com/home/thispageisdifferent/iswear', 'timestamp': 3241423}]

mockDataReordered = [{'visitorId': '1aUserOne', 'pageUrl': 'mock.com/home', 'timestamp': 1},
                     {'visitorId': '3cUserThree', 'pageUrl': 'mock.com/home/afterhome/afterafterhome','timestamp': 8932},
                     {'visitorId': '3cUserThree', 'pageUrl': 'mock.com/home', 'timestamp': 23323},
                     {'visitorId': '1aUserOne', 'pageUrl': 'mock.com/home/afterhome', 'timestamp': 10},
                     {'visitorId': '1aUserOne', 'pageUrl': 'mock.com/home/afterhome/afterafterhome', 'timestamp': 100},
                     {'visitorId': '2bUserTwo', 'pageUrl': 'mock.com/home', 'timestamp': 32},
                     {'visitorId': '1aUserOne',   'pageUrl': 'mock.com/home/thisshouldbealone', 'timestamp': 10000},
                     {'visitorId': '1aUserOne', 'pageUrl': 'mock.com/home', 'timestamp': 1000},
                     {'visitorId': '2bUserTwo', 'pageUrl': 'mock.com/home/afterhome', 'timestamp': 67},
                     {'visitorId': '3cUserThree', 'pageUrl': 'mock.com/home/thisshouldbealone', 'timestamp': 324142}]